services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  rate-limiter:
    build: ./rate-limiter
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RATE_LIMIT=5
      - WINDOW_SIZE=60

  service-a:
    build: ./services/service-a
    ports:
      - "3000:3000"
    environment:
      - SERVICE_NAME=Service A
      - PORT=3000

  service-b:
    build: ./services/service-b
    ports:
      - "3001:3001"
    environment:
      - SERVICE_NAME=Service B
      - PORT=3001

  service-c:
    build: ./services/service-c
    ports:
      - "3002:3002"
    environment:
      - SERVICE_NAME=Service C
      - PORT=3002

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service-a
      - service-b
      - service-c